from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, ConfigDict, Field
from app.models.enums import EventCategory
from app.schemas.recall import (
    CompetitorSummaryInfo,
    DateRangeInfo,
    TimelineEventItem,
    MemoryProvenanceItem,
)


class AgentAnalysisRequest(BaseModel):
    """Input payload for POST /api/v1/analyze competitive intelligence agent query."""

    query: str = Field(
        ...,
        min_length=1,
        json_schema_extra={"example": "What has Microsoft AI done in the last 90 days and what patterns can be observed?"},
        description="Natural language competitive intelligence analyst question.",
    )
    competitor_id: Optional[int] = Field(
        default=None,
        json_schema_extra={"example": 1},
        description="Optional explicit competitor ID filter.",
    )
    start_date: Optional[datetime] = Field(
        default=None,
        description="Optional explicit start date bounds (ISO 8601).",
    )
    end_date: Optional[datetime] = Field(
        default=None,
        description="Optional explicit end date bounds (ISO 8601).",
    )
    category: Optional[EventCategory] = Field(
        default=None,
        description="Optional explicit event category filter.",
    )


class AgentAnalysisResponse(BaseModel):
    """Structured response payload for POST /api/v1/analyze competitive intelligence agent analysis."""

    query: str
    status: str = Field(
        ...,
        json_schema_extra={"example": "success"},
        description="Execution status: success | degraded | missing_competitor | error",
    )
    competitor: Optional[CompetitorSummaryInfo] = None
    date_range: Optional[DateRangeInfo] = None
    summary: str = Field(..., description="Executive intelligence summary generated by Gemini LLM / Agent reasoning.")
    facts: List[str] = Field(
        default_factory=list,
        description="FACT: Directly supported by stored competitor events or Hindsight memories.",
    )
    observations: List[str] = Field(
        default_factory=list,
        description="OBSERVATION: Patterns derived from recorded facts.",
    )
    insights: List[str] = Field(
        default_factory=list,
        description="INSIGHT: Reasoned strategic interpretations grounded in evidence.",
    )
    evidence: List[TimelineEventItem] = Field(
        default_factory=list,
        description="Chronologically ordered timeline events provided to Gemini as evidence context.",
    )
    memory_sources: List[MemoryProvenanceItem] = Field(
        default_factory=list,
        description="Hindsight persistent memory provenance tracking records.",
    )
    memory_status: str = Field(
        default="connected",
        description="Hindsight persistent memory status: connected | unavailable | not_configured",
    )
    gemini_status: str = Field(
        default="connected",
        description="Google Gemini LLM status: connected | unavailable | not_configured",
    )
    grok_status: Optional[str] = Field(
        default=None,
        description="Optional legacy provider status compatibility field.",
    )
    limitations: List[str] = Field(
        default_factory=list,
        description="Declared analytical limitations or data availability constraints.",
    )

